[tool.poetry]
name = "qds"
version = "0.1.0"
description = "A Python wrapper for Quartz Display Services."
authors = ["Kamil Turek <kamil.turek@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
