---
name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4 
        with:
          python-version: '3.11'
      - name: Test
        run: |
          pip install -r requirements.txt
          pytest -s .
